### ISSUE TITLE
Using 'target' instead of 'targeted ...' doesn't work: IndexOutOfBoundsException

### ISSUE THREAD

**Issue by leroycep** [Njol/Skript#138]
2012-08-30 21:49:49 [SEVERE] ##!!
2012-08-30 21:49:49 [SEVERE] ##!! Severe Error:
2012-08-30 21:49:49 [SEVERE] ##!! Could not load magicbook.sk
2012-08-30 21:49:49 [SEVERE] ##!!
2012-08-30 21:49:49 [SEVERE] ##!! If you're developing an add-on for Skript this likely means you have done something wrong.
2012-08-30 21:49:49 [SEVERE] ##!! If you're a server admin, please go to http://dev.bukkit.org/server-mods/skript/tickets/
2012-08-30 21:49:49 [SEVERE] ##!! and create a new ticket with a meaningful title, copy & paste this whole error into it,
2012-08-30 21:49:49 [SEVERE] ##!! and please describe what you did before it happened and/or what you think caused the error.
2012-08-30 21:49:49 [SEVERE] ##!! If you feel like it's a trigger that's causing the error please post the trigger as well.
2012-08-30 21:49:49 [SEVERE] ##!! By following this guide fixing the error should be easy and done fast.
2012-08-30 21:49:49 [SEVERE] ##!!
2012-08-30 21:49:50 [SEVERE] ##!! Stacktrace:
2012-08-30 21:49:50 [SEVERE] ##!! java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
2012-08-30 21:49:50 [SEVERE] ##!! at java.util.ArrayList.rangeCheck(ArrayList.java:571)
2012-08-30 21:49:50 [SEVERE] ##!! at java.util.ArrayList.get(ArrayList.java:349)
2012-08-30 21:49:50 [SEVERE] ##!! at ch.njol.skript.expressions.ExprTarget.init(ExprTarget.java:53)
2012-08-30 21:49:50 [SEVERE] ##!! at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:264)
2012-08-30 21:49:50 [SEVERE] ##!! at ch.njol.skript.lang.SkriptParser.parseExpr(SkriptParser.java:317)
2012-08-30 21:49:50 [SEVERE] ##!! at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:529)
2012-08-30 21:49:50 [SEVERE] ##!! at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:233)
2012-08-30 21:49:50 [SEVERE] ##!! at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:201)
2012-08-30 21:49:50 [SEVERE] ##!! at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:173)
2012-08-30 21:49:50 [SEVERE] ##!! at ch.njol.skript.lang.Statement.parse(Statement.java:36)
2012-08-30 21:49:50 [SEVERE] ##!! at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:280)
2012-08-30 21:49:50 [SEVERE] ##!! at ch.njol.skript.lang.TriggerSection.<init>(TriggerSection.java:54)
2012-08-30 21:49:50 [SEVERE] ##!! at ch.njol.skript.lang.Conditional.<init>(Conditional.java:42)
2012-08-30 21:49:50 [SEVERE] ##!! at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:337)
2012-08-30 21:49:50 [SEVERE] ##!! at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:490)
2012-08-30 21:49:50 [SEVERE] ##!! at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:201)
2012-08-30 21:49:50 [SEVERE] ##!! at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:181)
2012-08-30 21:49:50 [SEVERE] ##!! at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:153)
2012-08-30 21:49:50 [SEVERE] ##!! at ch.njol.skript.Skript$1.run(Skript.java:216)
2012-08-30 21:49:50 [SEVERE] ##!! at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:126)
2012-08-30 21:49:50 [SEVERE] ##!! at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:510)
2012-08-30 21:49:50 [SEVERE] ##!! at net.minecraft.server.DedicatedServer.q(DedicatedServer.java:212)
2012-08-30 21:49:50 [SEVERE] ##!! at net.minecraft.server.MinecraftServer.p(MinecraftServer.java:474)
2012-08-30 21:49:50 [SEVERE] ##!! at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:406)
2012-08-30 21:49:50 [SEVERE] ##!! at net.minecraft.server.ThreadServerApplication.run(SourceFile:539)
2012-08-30 21:49:50 [SEVERE] ##!!
2012-08-30 21:49:50 [SEVERE] ##!! Version Information:
2012-08-30 21:49:50 [SEVERE] ##!! Skript: 1.4.9
2012-08-30 21:49:50 [SEVERE] ##!! Bukkit: 1.3.1-R2.0
2012-08-30 21:49:50 [SEVERE] ##!! Java: 1.6.0_24
2012-08-30 21:49:50 [SEVERE] ##!!
2012-08-30 21:49:50 [SEVERE] ##!! Running CraftBukkit: true
2012-08-30 21:49:50 [SEVERE] ##!!
2012-08-30 21:49:50 [SEVERE] ##!! Current node: target is an entity (magicbook.sk, line 19)
2012-08-30 21:49:50 [SEVERE] ##!!
2012-08-30 21:49:50 [SEVERE] ##!! End of Error.

**Comment by Njol** [comment]
Thank you for the report, as a temporary workaround you can use 'targeted entity' instead of 'target'.
