### ISSUE TITLE
Set a block at {location block} to a {id of block}

### ISSUE THREAD

**Issue by ghost** [Njol/Skript#210]
I want to store a location of a block, with id, and then set this block to a glass..
Then i want to restore this, in my variables i have the block location, and the id of the block.
When i do that : set block at {location} to {id block} the script just stop and print me a error in the logs :

2013-02-02 18:15:11 [SEVERE] ##!! 
2013-02-02 18:15:11 [SEVERE] ##!! [Skript] Severe Error:
2013-02-02 18:15:11 [SEVERE] ##!! 
2013-02-02 18:15:11 [SEVERE] ##!! If you're developping an add-on for Skript this likely means that you have done something wrong.
2013-02-02 18:15:11 [SEVERE] ##!! If you're a server admin however please go to http://dev.bukkit.org/server-mods/skript/tickets/
2013-02-02 18:15:11 [SEVERE] ##!! and check whether this error has already been reported.
2013-02-02 18:15:11 [SEVERE] ##!! If not please create a new ticket with a meaningful title, copy & paste this whole error into it,
2013-02-02 18:15:11 [SEVERE] ##!! and describe what you did before it happened and/or what you think caused the error.
2013-02-02 18:15:11 [SEVERE] ##!! If you feel like it's a trigger that's causing the error please post the trigger as well.
2013-02-02 18:15:11 [SEVERE] ##!! By following this guide fixing the error should be easy and done fast.
2013-02-02 18:15:11 [SEVERE] ##!! 
2013-02-02 18:15:11 [SEVERE] ##!! Stacktrace:
2013-02-02 18:15:11 [SEVERE] ##!! java.lang.NullPointerException
2013-02-02 18:15:11 [SEVERE] ##!!     at ch.njol.skript.classes.data.DefaultChangers$6.change(DefaultChangers.java:273)
2013-02-02 18:15:11 [SEVERE] ##!!     at ch.njol.skript.classes.data.DefaultChangers$6.change(DefaultChangers.java:1)
2013-02-02 18:15:11 [SEVERE] ##!!     at ch.njol.skript.classes.Changer$ChangerUtils.change(Changer.java:69)
2013-02-02 18:15:11 [SEVERE] ##!!     at ch.njol.skript.effects.EffChange.execute(EffChange.java:176)
2013-02-02 18:15:11 [SEVERE] ##!!     at ch.njol.skript.lang.Effect.run(Effect.java:50)
2013-02-02 18:15:11 [SEVERE] ##!!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:60)
2013-02-02 18:15:11 [SEVERE] ##!!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:82)
2013-02-02 18:15:11 [SEVERE] ##!!     at ch.njol.skript.effects.Delay$1.run(Delay.java:72)
2013-02-02 18:15:11 [SEVERE] ##!!     at org.bukkit.craftbukkit.v1_4_6.scheduler.CraftTask.run(CraftTask.java:53)
2013-02-02 18:15:11 [SEVERE] ##!!     at org.bukkit.craftbukkit.v1_4_6.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:345)
2013-02-02 18:15:11 [SEVERE] ##!!     at net.minecraft.server.v1_4_6.MinecraftServer.r(MinecraftServer.java:530)
2013-02-02 18:15:11 [SEVERE] ##!!     at net.minecraft.server.v1_4_6.DedicatedServer.r(DedicatedServer.java:224)
2013-02-02 18:15:11 [SEVERE] ##!!     at net.minecraft.server.v1_4_6.MinecraftServer.q(MinecraftServer.java:494)
2013-02-02 18:15:11 [SEVERE] ##!!     at net.minecraft.server.v1_4_6.MinecraftServer.run(MinecraftServer.java:427)
2013-02-02 18:15:11 [SEVERE] ##!!     at net.minecraft.server.v1_4_6.ThreadServerApplication.run(SourceFile:849)
2013-02-02 18:15:11 [SEVERE] ##!! 
2013-02-02 18:15:11 [SEVERE] ##!! Version Information:
2013-02-02 18:15:11 [SEVERE] ##!!   Skript: 2.0 beta 6
2013-02-02 18:15:11 [SEVERE] ##!!   Bukkit: 1.4.6-R0.3
2013-02-02 18:15:11 [SEVERE] ##!!   Java: 1.7.0
2013-02-02 18:15:11 [SEVERE] ##!! 
2013-02-02 18:15:11 [SEVERE] ##!! Running CraftBukkit: false
2013-02-02 18:15:11 [SEVERE] ##!! 
2013-02-02 18:15:11 [SEVERE] ##!! Current node: null
2013-02-02 18:15:11 [SEVERE] ##!! Current item: set the block (at {laserlocation.%{thecaster}(as java.lang.Object)%.%{laserlocation.%{thecaster}(as java.lang.Object)%.counterlaser}(as java.lang.Object)%.laser}(as org.bukkit.Location))->org.bukkit.block.Block to {blabla}(as ch.njol.skript.util.ItemType)
2013-02-02 18:15:11 [SEVERE] ##!! 
2013-02-02 18:15:11 [SEVERE] ##!! Current thread: Server thread
2013-02-02 18:15:11 [SEVERE] ##!! 
2013-02-02 18:15:11 [SEVERE] ##!! End of Error.
2013-02-02 18:15:11 [SEVERE] ##!! 

This is pretty important, because with this bug, you cant set blocks, and then rollback this blocks, so, no saving blocks (sigh T_T), no backup of areas or radius.. Well, the "set block at" function is in one way, no way to get it back :'(

If you want some more infos, dont hesitate ;)

**Comment by Njol** [comment]
This error will be fixed in the next beta. You'll have to change your script a bit though as what currently produces this error will simply not do anything in the next version; You likely have to change {id of block} from a number to an item type (e.g. from '1' to 'stone').

BTW: please use Bukkit's ticket system as mentioned in the error message next time for reporting bugs ;)
