### ISSUE TITLE
Crash on console skript 2.0

### ISSUE THREAD

**Issue by Pilvinen** [Njol/Skript#251]
It just happened all of a sudden for no apparent reason:

Skript 2.0
Spigot 1.6.4 build 1112

And no, I'm not developing add-on for skript or doing anything out of ordinary. No new scripts have been added. Don't know what is going on.

EDIT: Don't know if this is in any way related but Mojang session server & login servers were down at the time.

2013-09-21 16:35:44 [SEVERE] #!#! 
2013-09-21 16:35:44 [SEVERE] #!#! [Skript] Severe Error:
2013-09-21 16:35:44 [SEVERE] #!#! 
2013-09-21 16:35:44 [SEVERE] #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
2013-09-21 16:35:44 [SEVERE] #!#! If you're a server admin however please go to http://dev.bukkit.org/server-mods/skript/tickets/
2013-09-21 16:35:44 [SEVERE] #!#! and check whether this error has already been reported.
2013-09-21 16:35:44 [SEVERE] #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it,
2013-09-21 16:35:44 [SEVERE] #!#! and describe what you did before it happened and/or what you think caused the error.
2013-09-21 16:35:44 [SEVERE] #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
2013-09-21 16:35:44 [SEVERE] #!#! By following this guide fixing the error should be easy and done fast.
2013-09-21 16:35:44 [SEVERE] #!#! 
2013-09-21 16:35:44 [SEVERE] #!#! Stack trace:
2013-09-21 16:35:44 [SEVERE] #!#! java.lang.ArrayIndexOutOfBoundsException: 4
2013-09-21 16:35:44 [SEVERE] #!#!     at net.minecraft.server.v1_6_R3.PlayerInventory.getItem(PlayerInventory.java:404)
2013-09-21 16:35:44 [SEVERE] #!#!     at org.bukkit.craftbukkit.v1_6_R3.inventory.CraftInventory.getItem(CraftInventory.java:49)
2013-09-21 16:35:44 [SEVERE] #!#!     at ch.njol.skript.expressions.ExprItemsIn$1.next(ExprItemsIn.java:110)
2013-09-21 16:35:44 [SEVERE] #!#!     at ch.njol.skript.expressions.ExprItemsIn$1.next(ExprItemsIn.java:1)
2013-09-21 16:35:44 [SEVERE] #!#!     at ch.njol.skript.lang.Loop.walk(Loop.java:98)
2013-09-21 16:35:44 [SEVERE] #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:87)
2013-09-21 16:35:44 [SEVERE] #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:52)
2013-09-21 16:35:44 [SEVERE] #!#!     at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:135)
2013-09-21 16:35:44 [SEVERE] #!#!     at ch.njol.skript.SkriptEventHandler$1.execute(SkriptEventHandler.java:98)
2013-09-21 16:35:44 [SEVERE] #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
2013-09-21 16:35:44 [SEVERE] #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:478)
2013-09-21 16:35:44 [SEVERE] #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:463)
2013-09-21 16:35:44 [SEVERE] #!#!     at net.minecraft.server.v1_6_R3.PlayerConnection.a(PlayerConnection.java:1115)
2013-09-21 16:35:44 [SEVERE] #!#!     at net.minecraft.server.v1_6_R3.Packet7UseEntity.handle(SourceFile:36)
2013-09-21 16:35:44 [SEVERE] #!#!     at org.spigotmc.netty.NettyNetworkManager.b(NettyNetworkManager.java:230)
2013-09-21 16:35:44 [SEVERE] #!#!     at net.minecraft.server.v1_6_R3.PlayerConnection.e(PlayerConnection.java:116)
2013-09-21 16:35:44 [SEVERE] #!#!     at net.minecraft.server.v1_6_R3.ServerConnection.b(SourceFile:37)
2013-09-21 16:35:44 [SEVERE] #!#!     at org.spigotmc.netty.NettyServerConnection.b(NettyServerConnection.java:132)
2013-09-21 16:35:44 [SEVERE] #!#!     at net.minecraft.server.v1_6_R3.MinecraftServer.t(MinecraftServer.java:594)
2013-09-21 16:35:44 [SEVERE] #!#!     at net.minecraft.server.v1_6_R3.DedicatedServer.t(DedicatedServer.java:240)
2013-09-21 16:35:44 [SEVERE] #!#!     at net.minecraft.server.v1_6_R3.MinecraftServer.s(MinecraftServer.java:483)
2013-09-21 16:35:44 [SEVERE] #!#!     at net.minecraft.server.v1_6_R3.MinecraftServer.run(MinecraftServer.java:415)
2013-09-21 16:35:44 [SEVERE] #!#!     at net.minecraft.server.v1_6_R3.ThreadServerApplication.run(SourceFile:583)
2013-09-21 16:35:44 [SEVERE] #!#! 
2013-09-21 16:35:44 [SEVERE] #!#! Version Information:
2013-09-21 16:35:44 [SEVERE] #!#!   Skript: 2.0
2013-09-21 16:35:44 [SEVERE] #!#!   Bukkit: 1.6.4-R0.1-SNAPSHOT
2013-09-21 16:35:44 [SEVERE] #!#!   Minecraft: 1.6.4
2013-09-21 16:35:44 [SEVERE] #!#!   Java: 1.7.0_40
2013-09-21 16:35:44 [SEVERE] #!#! 
2013-09-21 16:35:44 [SEVERE] #!#! Running CraftBukkit: false
2013-09-21 16:35:44 [SEVERE] #!#! 
2013-09-21 16:35:44 [SEVERE] #!#! Current node: null
2013-09-21 16:35:44 [SEVERE] #!#! Current item: null
2013-09-21 16:35:44 [SEVERE] #!#! 
2013-09-21 16:35:44 [SEVERE] #!#! Thread: Server thread
2013-09-21 16:35:44 [SEVERE] #!#! 
2013-09-21 16:35:44 [SEVERE] #!#! End of Error.
2013-09-21 16:35:44 [SEVERE] #!#!

**Comment by joeuguce99** [comment]
Try the latest spigot build, otherwise the latest bukkit dev build.

**Comment by Pilvinen** [comment]
Are you being absolutely serious? Build 1112 at the time of the writing is the very latest.

Why do I even bother reporting these bugs ...

**Comment by zmolahah** [comment]
No need to be rude. I'm sure it will be fixed soon enough

**Comment by Mirreski** [comment]
Take in mind that all people are not using Spigot so how are we going to know if you are using the latest version without checking it out.

**Comment by Pilvinen** [comment]
By checking it out before posting.

**Comment by Mirreski** [comment]
Or you could have wrote that you used the latest version. No point in arguing about this, It was just a suggestion.

So have you tried with the Latest Bukkit Dev? Is it working?

**Comment by joeuguce99** [comment]
Just in case you missed these lines in the report,

2013-09-21 16:35:44 [SEVERE] #!#! If you're a server admin however please go to http://dev.bukkit.org/server-mods/skript/tickets/
2013-09-21 16:35:44 [SEVERE] #!#! and check whether this error has already been reported.
2013-09-21 16:35:44 [SEVERE] #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it,
2013-09-21 16:35:44 [SEVERE] #!#! and describe what you did before it happened and/or what you think caused the error.
