### ISSUE TITLE
Setting signs doesn't seem to work in 2.1

### ISSUE THREAD

**Issue by Parrothead** [Njol/Skript#275]
The syntax used worked in 2.0.  I don't think I'm doing anything wrong as I read the changelog.

[17:12:25] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[17:12:25] [Server thread/ERROR]: #!#! Unexpected error while executing effect command 'set line 4 of the block at {eventupdatesign.a3} to "%{dungeon.string.15}%"' by 'Parrothead'
[17:12:25] [Server thread/ERROR]: #!#! 
[17:12:25] [Server thread/ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[17:12:25] [Server thread/ERROR]: #!#! If you're a server admin however please go to http://dev.bukkit.org/server-mods/skript/tickets/
[17:12:25] [Server thread/ERROR]: #!#! and check whether this error has already been reported.
[17:12:25] [Server thread/ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it,
[17:12:25] [Server thread/ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[17:12:25] [Server thread/ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[17:12:25] [Server thread/ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[17:12:25] [Server thread/ERROR]: #!#! 
[17:12:25] [Server thread/ERROR]: #!#! Stack trace:
[17:12:25] [Server thread/ERROR]: #!#! java.lang.NullPointerException
[17:12:25] [Server thread/ERROR]: #!#!     at ch.njol.skript.util.Utils.a(Utils.java:302)
[17:12:25] [Server thread/ERROR]: #!#!     at ch.njol.skript.util.Utils.a(Utils.java:277)
[17:12:25] [Server thread/ERROR]: #!#!     at ch.njol.skript.expressions.base.EventValueExpression.init(EventValueExpression.java:133)
[17:12:25] [Server thread/ERROR]: #!#!     at ch.njol.skript.expressions.ExprBlock.init(ExprBlock.java:78)
[17:12:25] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:228)
[17:12:25] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:159)
[17:12:25] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:472)
[17:12:25] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:281)
[17:12:25] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:940)
[17:12:25] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:858)
[17:12:25] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:931)
[17:12:25] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:865)
[17:12:25] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:200)
[17:12:25] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:159)
[17:12:25] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:472)
[17:12:25] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:281)
[17:12:25] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:940)
[17:12:25] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:200)
[17:12:25] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:159)
[17:12:25] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:472)
[17:12:25] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseObjectExpression(SkriptParser.java:356)
[17:12:25] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:273)
[17:12:25] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:940)
[17:12:25] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:200)
[17:12:25] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:159)
[17:12:25] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Effect.parse(Effect.java:56)
[17:12:25] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands.handleEffectCommand(Commands.java:258)
[17:12:25] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands$4$1.call(Commands.java:201)
[17:12:25] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands$4$1.call(Commands.java:1)
[17:12:25] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftFuture.run(CraftFuture.java:89)
[17:12:25] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:345)
[17:12:25] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_7_R1.MinecraftServer.u(MinecraftServer.java:577)
[17:12:25] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_7_R1.DedicatedServer.u(DedicatedServer.java:259)
[17:12:25] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_7_R1.MinecraftServer.t(MinecraftServer.java:534)
[17:12:25] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_7_R1.MinecraftServer.run(MinecraftServer.java:446)
[17:12:25] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_7_R1.ThreadServerApplication.run(SourceFile:617)
[17:12:25] [Server thread/ERROR]: #!#! 
[17:12:25] [Server thread/ERROR]: #!#! Version Information:
[17:12:25] [Server thread/ERROR]: #!#!   Skript: 2.1
[17:12:25] [Server thread/ERROR]: #!#!   Bukkit: 1.7.2-R0.1-SNAPSHOT
[17:12:25] [Server thread/ERROR]: #!#!   Minecraft: 1.7.2
[17:12:25] [Server thread/ERROR]: #!#!   Java: 1.7.0_45
[17:12:25] [Server thread/ERROR]: #!#! 
[17:12:25] [Server thread/ERROR]: #!#! Running CraftBukkit: false
[17:12:25] [Server thread/ERROR]: #!#! 
[17:12:25] [Server thread/ERROR]: #!#! Current node: null
[17:12:25] [Server thread/ERROR]: #!#! Current item: null
[17:12:25] [Server thread/ERROR]: #!#! 
[17:12:25] [Server thread/ERROR]: #!#! Thread: Server thread
[17:12:25] [Server thread/ERROR]: #!#! 
[17:12:25] [Server thread/ERROR]: #!#! End of Error.
[17:12:25] [Server thread/ERROR]: #!#!

**Comment by MostFunGuy** [comment]
Post your code with it as well.

**Comment by Parrothead** [comment]
Certain formats of the code in combination with certain actions do not perpetrate any errors, but the sign still doesn't get set.  I've noticed that if the event involves a command trigger, an error won't be thrown out.  For more info, visit (dev.bukkit.org/bukkit-plugins/skript/forum/help/60524-setting-sign-text/).

command /winner1 <text>:
    description: Gives debugging help.
    permission: skript.admin
    trigger:
        if argument 1 is "zephyr":
            loop blocks in radius 50 of {castlewool}:
                loop-block is wool:
                    set loop-block to red wool
        if argument 1 is "abyssal":
            set line 4 of the block at {eventupdatesign.a4} to "%{dungeon.string.15}%"  

edit: The code doesn't format correctly, here's a screenshot (http://i.imgur.com/CGCWrls.jpg).  The trigger above will not throw out an error, but it still doesn't work.

**Comment by Njol** [comment]
Will be fixed in the next version.
