### ISSUE TITLE
Erron on damaging somebody

### ISSUE THREAD

**Issue by ghost** [Njol/Skript#330]
I didn't know whether it was a bug. It appeared when I was damaged by a zombie and damaged zombie too. Sorry for this unclear information. Here's log:

2014-04-17 17:07:46 [SEVERE] Could not pass event EntityDamageByEntityEvent to Skript v2.1.2
java.lang.NoClassDefFoundError: Could not initialize class ch.njol.skript.bukkitutil.ProjectileUtils
        at ch.njol.skript.expressions.ExprAttacker.getAttacker(ExprAttacker.java:85)
        at ch.njol.skript.expressions.ExprAttacker.get(ExprAttacker.java:76)
        at ch.njol.skript.expressions.ExprAttacker.get(ExprAttacker.java:1)
        at ch.njol.skript.lang.util.SimpleExpression.check(SimpleExpression.java:160)
        at ch.njol.skript.lang.util.SimpleExpression.check(SimpleExpression.java:155)
        at ch.njol.skript.lang.util.ConvertedExpression.check(ConvertedExpression.java:173)
        at ch.njol.skript.hooks.regions.conditions.CondCanBuild.check(CondCanBuild.java:79)
        at ch.njol.skript.lang.Condition.run(Condition.java:58)
        at ch.njol.skript.lang.Conditional.walk(Conditional.java:51)
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:91)
        at ch.njol.skript.lang.Trigger.execute(Trigger.java:53)
        at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:149)
        at ch.njol.skript.SkriptEventHandler$1.execute(SkriptEventHandler.java:109)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:479)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:464)
        at org.bukkit.craftbukkit.v1_6_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:80)
        at org.bukkit.craftbukkit.v1_6_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:423)
        at org.bukkit.craftbukkit.v1_6_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:452)
        at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:967)
        at net.minecraft.entity.monster.EntityMob.func_70097_a(EntityMob.java:76)
        at net.minecraft.entity.monster.EntityZombie.func_70097_a(EntityZombie.java:215)
        at net.minecraft.entity.projectile.EntityArrow.func_70071_h_(EntityArrow.java:331)
        at net.minecraft.world.World.func_72866_a(World.java:2944)
        at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:1006)
        at net.minecraft.world.World.func_72870_g(World.java:2890)
        at net.minecraft.world.World.func_72939_s(World.java:2704)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:883)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:330)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:777)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:659)
        at net.minecraft.server.ThreadMinecraftServer.run(ThreadMinecraftServer.java:16)

**Comment by Zerkhan** [comment]
Hi ! Can you specify your Bukkit/Spigot version, and the content of your script ?

**Comment by ghost** [comment]
MCPC+ v251, I didn't know whether it was a troubled script. It happened occassionally, I have no clue. Does github have PMs? Then I can write private message to you with all my sxripts.

**Comment by Zerkhan** [comment]
I don't know about PMs :c Sometimes, modifying the script's "behavior" can solve errors. But if this error is a bug, only Njol can help you.

**Comment by ghost** [comment]
Closing this, I think it makes no odds.
