### ISSUE TITLE
loop blocks in radius 10 around the event-block - Error

### ISSUE THREAD

**Issue by MorkaZ** [Njol/Skript#373]
Skript: 2.2
Spigot 1.7&1.8 Protocol hack

1.
[Skript]
on leftclick:
    loop blocks in radius 10 around the event-block:
        if loop-block is portal:
            cancel event
            send "&f[&9GC&b2&f] &cW okolicy znajduje sie portal, nie mozesz wiec tego tutaj uzyc."
            stop

[Console]
[09:10:15] [Server thread/ERROR]: #!#! 
[09:10:15] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[09:10:15] [Server thread/ERROR]: #!#! Could not load dupa.sk
[09:10:15] [Server thread/ERROR]: #!#! 
[09:10:15] [Server thread/ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[09:10:15] [Server thread/ERROR]: #!#! If you're a server admin however please go to http://dev.bukkit.org/server-mods/skript/tickets/
[09:10:15] [Server thread/ERROR]: #!#! and check whether this error has already been reported.
[09:10:15] [Server thread/ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it,
[09:10:15] [Server thread/ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[09:10:15] [Server thread/ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[09:10:15] [Server thread/ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[09:10:15] [Server thread/ERROR]: #!#! 
[09:10:15] [Server thread/ERROR]: #!#! Stack trace:
[09:10:15] [Server thread/ERROR]: #!#! java.lang.NullPointerException
[09:10:15] [Server thread/ERROR]: #!#!     at net.milkbowl.vault.economy.plugins.Economy_Craftconomy3.currencyNameSingular(Economy_Craftconomy3.java:113)
[09:10:15] [Server thread/ERROR]: #!#!     at ch.njol.skript.hooks.economy.classes.Money.parse(Money.java:146)
[09:10:15] [Server thread/ERROR]: #!#!     at ch.njol.skript.hooks.economy.classes.Money$1.parse(Money.java:59)
[09:10:15] [Server thread/ERROR]: #!#!     at ch.njol.skript.hooks.economy.classes.Money$1.parse(Money.java:1)
[09:10:15] [Server thread/ERROR]: #!#!     at ch.njol.skript.registrations.Classes.parseSimple(Classes.java:400)
[09:10:15] [Server thread/ERROR]: #!#!     at ch.njol.skript.registrations.Classes.parse(Classes.java:439)
[09:10:15] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:354)
[09:10:15] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:398)
[09:10:15] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1117)
[09:10:15] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1042)
[09:10:15] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1042)
[09:10:15] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1108)
[09:10:15] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:216)
[09:10:15] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:171)
[09:10:15] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:316)
[09:10:15] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:398)
[09:10:15] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1117)
[09:10:15] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1069)
[09:10:15] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:216)
[09:10:15] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:171)
[09:10:15] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:316)
[09:10:15] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:398)
[09:10:15] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:668)
[09:10:15] [Server thread/ERROR]: #!#!     at ch.njol.skript.command.Commands.loadCommand(Commands.java:466)
[09:10:15] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:469)
[09:10:15] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:268)
[09:10:15] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:155)
[09:10:15] [Server thread/ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[09:10:15] [Server thread/ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181)
[09:10:15] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:767)
[09:10:15] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_7_R4.PlayerConnection.handleCommand(PlayerConnection.java:1043)
[09:10:15] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:880)
[09:10:15] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_7_R4.PacketPlayInChat.a(PacketPlayInChat.java:28)
[09:10:15] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_7_R4.PacketPlayInChat.handle(PacketPlayInChat.java:65)
[09:10:15] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:186)
[09:10:15] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81)
[09:10:15] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734)
[09:10:15] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289)
[09:10:15] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584)
[09:10:15] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490)
[09:10:15] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)
[09:10:15] [Server thread/ERROR]: #!#! 
[09:10:15] [Server thread/ERROR]: #!#! Version Information:
[09:10:15] [Server thread/ERROR]: #!#!   Skript: 2.2-SNAPSHOT
[09:10:15] [Server thread/ERROR]: #!#!   Bukkit: 1.7.10-R0.1-SNAPSHOT
[09:10:15] [Server thread/ERROR]: #!#!   Minecraft: 1.7.10
[09:10:15] [Server thread/ERROR]: #!#!   Java: 1.7.0_80 (Java HotSpot(TM) 64-Bit Server VM 24.80-b11)
[09:10:15] [Server thread/ERROR]: #!#!   OS: Linux amd64 3.14.32-xxxx-grs-ipv6-64
[09:10:15] [Server thread/ERROR]: #!#! 
[09:10:15] [Server thread/ERROR]: #!#! Running CraftBukkit: false
[09:10:15] [Server thread/ERROR]: #!#! 
[09:10:15] [Server thread/ERROR]: #!#! Current node: loop blocks in radius 10 around the event-block: (dupa.sk, line 43)
[09:10:15] [Server thread/ERROR]: #!#! Current item: null
[09:10:15] [Server thread/ERROR]: #!#! 
[09:10:15] [Server thread/ERROR]: #!#! Thread: Server thread
[09:10:15] [Server thread/ERROR]: #!#! 
[09:10:15] [Server thread/ERROR]: #!#! End of Error.
[09:10:15] [Server thread/ERROR]: #!#!

**Comment by MorkaZ** [comment]
2.
Parsing text to enchantment does not work (tested with newest spigot). 
Example:
set {_test} to "sharpness 2" parsed as enchantment
enchant player's tool with {_test}

Effect:
Player's tool is not enchanted. Skript did nothing.

**Comment by MorkaZ** [comment]
3.
formating slot in current inventory is formating effects also in player's inventory up from 2 row.

**Comment by MorkaZ** [comment]
4.
Operations on regions is not working at 80% with Worldguard 6.0+
Also, checking that player is an owner of region, when regions are set in list variable is not working propetly in worlguard 5 +. Checked also in older spigot versions and newests. Same result.
