### ISSUE TITLE
Error when broadcasting a message

### ISSUE THREAD

**Issue by ghost** [Njol/Skript#378]
When my skript uses the 

broadcast "Message"

the console outputs this...
[22:18:05 WARN]: [Skript] Task #24 for Skript v2.1.2 generated an exception
java.lang.NoSuchMethodError: org.bukkit.Bukkit.getOnlinePlayers()[Lorg/bukkit/en
tity/Player;
        at ch.njol.skript.effects.EffBroadcast.execute(EffBroadcast.java:72) ~[?
:?]
        at ch.njol.skript.lang.Effect.run(Effect.java:50) ~[?:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:63) ~[?:?]
        at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:91) ~[?:?]
        at ch.njol.skript.lang.Trigger.execute(Trigger.java:53) ~[?:?]
        at ch.njol.skript.events.EvtChat$1.execute(EvtChat.java:68) ~[?:?]
        at ch.njol.skript.events.EvtChat$1$1.call(EvtChat.java:87) ~[?:?]
        at ch.njol.skript.events.EvtChat$1$1.call(EvtChat.java:1) ~[?:?]
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftFuture.run(CraftFuture
.java:89) ~[spigot.jar:git-Spigot-f9671b8-48b88ed]
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHe
artbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-f9671b8-48b88ed]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:
723) [spigot.jar:git-Spigot-f9671b8-48b88ed]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:
400) [spigot.jar:git-Spigot-f9671b8-48b88ed]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:
668) [spigot.jar:git-Spigot-f9671b8-48b88ed]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.jav
a:567) [spigot.jar:git-Spigot-f9671b8-48b88ed]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]

**Comment by Njol** [comment]
Looks like Skript is not compatible with the newest version of Bukkit 
any more. Try to find an updated version of Skript, I heard that there 
are forks of it - just search the Bukkit site and you might find one (I 
don't work on Skript any more, so I don't know a lot of what is happening).

Am 29.09.2016 um 04:21 schrieb Nick S:

**Comment by ghost** [comment]
Alright, thanks for the reply. I found a v2.2 on skunity.com but Dropbox is broken. I'll try to find a fork, thanks.

**Comment by Legoman99573** [comment]
Use Bensku's fork, its more up-to-date.
